### ISSUE TITLE
leader gb does open the gh browse

### ISSUE THREAD

**Issue by biehlera** [steinbrueckri/dotfiles#50]
keymap is defined in keymap.lua but does not work.
Pls fix.

**Comment by steinbrueckri** [comment]
https://github.com/steinbrueckri/dotfiles/commit/ce64f19660c1d035c4a388bf47c269f7f50e40df#diff-1a7cddf308ee93872e462b5a7e8dfa2d4f28b8a78023078290da98638023edd3
